steps:
  # Build the frontend
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    dir: 'frontend'
  
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'frontend'
  
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/visa-chatbot-frontend:$COMMIT_SHA', '.']
    dir: 'frontend'
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/visa-chatbot-frontend:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'visa-chatbot-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/visa-chatbot-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'

images:
  - 'gcr.io/$PROJECT_ID/visa-chatbot-frontend:$COMMIT_SHA'
