name: Auto-Deploy to Google Cloud

# Force new deployment - added Service Account User permissions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-backend:
    name: Deploy Backend to Cloud Run
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Verify Authentication
      run: |
        echo "=== Current working directory ==="
        pwd
        echo "=== Listing files ==="
        ls -la
        echo "=== Google Cloud Auth Status ==="
        gcloud auth list
        echo "=== Google Cloud Config ==="
        gcloud config list
        echo "=== Setting Project ==="
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        echo "=== Verifying Project ==="
        gcloud config get-value project
    
    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker
        gcloud auth list
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ai-chatbot-backend \
          --source ./backend \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 1 \
          --set-env-vars ENVIRONMENT=production

  deploy-frontend:
    name: Deploy Frontend to Cloud Storage
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Deploy to Cloud Storage
      run: |
        gsutil -m rsync -r -d frontend/dist/ gs://ai-chatbot-jb020725-frontend/
        gsutil web set -m index.html -e index.html gs://ai-chatbot-jb020725-frontend/
        gsutil acl ch -r -u AllUsers:R gs://ai-chatbot-jb020725-frontend/
