name: Auto-Deploy to Google Cloud

# Force new deployment - added Cloud Build permissions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-backend:
    name: Deploy Backend to Cloud Run
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Verify Authentication
      run: |
        echo "=== Current working directory ==="
        pwd
        echo "=== Listing files ==="
        ls -la
        echo "=== Google Cloud Auth Status ==="
        gcloud auth list
        echo "=== Google Cloud Config ==="
        gcloud config list
        echo "=== Setting Project ==="
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        echo "=== Verifying Project ==="
        gcloud config get-value project
    
    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker
        gcloud auth list
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ai-chatbot-backend \
          --source ./backend \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 1 \
          --set-env-vars ENVIRONMENT=production

  # Frontend deployment skipped - already deployed successfully
  # deploy-frontend:
  #   name: Deploy Frontend to Cloud Storage
  #   runs-on: ubuntu-latest
  #   if: false  # Skip frontend deployment
