name: Test GitHub Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Test Google Cloud Setup
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Verify Authentication
      run: |
        echo "Project ID: ${{ secrets.GCP_PROJECT_ID }}"
        echo "Service Account Key exists: ${{ secrets.GCP_SA_KEY != '' }}"
        gcloud auth list
        gcloud config list
